import React, { useEffect, useState } from 'react'
import { usePathname } from 'next/navigation'
import { useAuth } from '@/context/auth'
import { useData } from '@/context/data'
import DateDisplay from '@/utils/CreatedAtDateConversion/createdAtDateConversion'
import Checkbox from '@mui/material/Checkbox'

import SearchResultCardComponent from '../SearchResultCardComponent/SearchResultCardComponent'
import TooltipComponent from '../Tooltip'
import AdvancedEditor from './advanceFilter'
import styles from './PropertyDetails.module.css'
import { COMPONENTS, GLOBALLY_COMMON_TEXT } from '@/textV2'
const label = { inputProps: { 'aria-label': 'Checkbox demo' } }
const maroon = '#931602'
const { stepFive } = COMPONENTS.POST_PROPERTY_COMPO
const { individualText, agentText, ownerText, representativeText } = GLOBALLY_COMMON_TEXT.text
export default function Step5({
  DATA,
  setDATA,
  setPropertyDetails,
  setDeclarationOne,
  setDeclarationTwo,
  declarationOne,
  declarationTwo,
  edit,
  setRole,
  role,
  privacyPolicy,
  setPrivacyPolicy,
}) {
  useEffect(() => {
    if (typeof DATA?.salePrice === 'string' && DATA?.salePrice.includes(',')) {
      setDATA({
        ...DATA,
        salePrice: DATA?.salePrice.replace(/\D/g, ''), // Removes all non-numeric characters
      })
    }
    else if (typeof DATA?.rentPrice === 'string' && DATA?.rentPrice.includes(',')) {
      setDATA({
        ...DATA,
        rentPrice: DATA?.rentPrice.replace(/\D/g, ''), // Removes all non-numeric characters
      })
    }
    else if (typeof DATA?.rentDepositAmount === 'string' && DATA?.rentDepositAmount.includes(',')) {
      setDATA({
        ...DATA,
        rentDepositAmount: DATA?.rentDepositAmount.replace(/\D/g, ''), // Removes all non-numeric characters
      })
    }
    else if (typeof DATA?.maintenanceAmount === 'string' && DATA?.maintenanceAmount.includes(',')) {
      setDATA({
        ...DATA,
        maintenanceAmount: DATA?.maintenanceAmount.replace(/\D/g, ''),
      })
    }
  }, [])

  const [data, setData] = useData()
  const [isAuto, setIsAuto] = useState(false)
  const pathname = usePathname()
  const urlParams = new URLSearchParams(window.location.search)
  const propId = urlParams.get('propertyId')
  let date = new Date().toJSON()
  const daysAgo = DateDisplay(date)
  const propertyDescription = DATA?.propertyDescription || ''
  const handlePropertyDescriptionChange = (content) => {
    setDATA({
      ...DATA,
      propertyDescription: content,
      isDescriptionAutoGenerated: isAuto,
    })
  }
  const [auth] = useAuth()
  let imageArray = []
  // const { propertyCoverImage, projectCoverImage } = DATA || {}
  // if (propertyCoverImage) {
  //   imageArray.push(propertyCoverImage)
  // } else if (projectCoverImage) {
  //   imageArray.push(projectCoverImage)
  // }
  DATA?.propertyImages?.forEach((element) => {
    imageArray.push(element.url)
  })
  DATA?.projectImages?.forEach((element) => {
    imageArray.push(element.url)
  })


  useEffect(() => {
    if (typeof DATA?.salePrice === 'string' && DATA?.salePrice.includes(',')) {
      setDATA({
        ...DATA,
        salePrice: DATA?.salePrice.replace(/\D/g, ''),
      })
    }
    else if (typeof DATA?.rentPrice === 'string' && DATA?.rentPrice.includes(',')) {
      setDATA({
        ...DATA,
        rentPrice: DATA?.rentPrice.replace(/\D/g, ''),
      })
    }
    else if (typeof DATA?.rentDepositAmount === 'string' && DATA?.rentDepositAmount.includes(',')) {
      setDATA({
        ...DATA,
        rentDepositAmount: DATA?.rentDepositAmount.replace(/\D/g, ''),
      })
    }
    else if (typeof DATA?.maintenanceAmount === 'string' && DATA?.maintenanceAmount.includes(',')) {
      setDATA({
        ...DATA,
        maintenanceAmount: DATA?.maintenanceAmount.replace(/\D/g, ''),
      })
    }
  }, [DATA])

  const {
    addressLabel = '',
    bedroomCount = '',
    bathroomCount = '',
    furnishingStatus = '',
    propertyTitle = '',
    salePrice = '',
    rentPrice = '',
    projectDescription = '',
    propertyDescription: PropertyDescription = '',
    propertyType = '',
    projectType = '',
    propertySubType = '',
    projectSubType = '',
    areaDetail,
    postedAs,
  } = DATA || {}

  useEffect(() => {
    if (DATA?.propertyDescription && DATA?.propertyDescription.length > 0) {
      if (auth?.userResult?.userType === individualText) {
        if (postedAs?.trim() !== '') {
          setPropertyDetails(true)
        } else {
          setPropertyDetails(false)
        }
      } else {
        setPropertyDetails(true)
      }
    } else {
      setPropertyDetails(false)
    }
  }, [DATA, propertyDescription, postedAs])
  if (DATA) {
    DATA.bedroomCount = bedroomCount === '4+' ? '4' : bedroomCount
    DATA.bathroomCount = bathroomCount === '4+' ? '4' : bathroomCount
  }
  const filteredDetail = areaDetail?.filter((detail) => detail.display)

  let propertySize, propertySizeUnit
  if (DATA?.propertySize) {
    propertySize = DATA?.propertySize
    propertySizeUnit = DATA?.propertySizeUnit
  }
  
  else if (filteredDetail?.length > 0) {
     ({ propertySize, propertySizeUnit } = filteredDetail[0])
  }

  const firstName = auth?.userResult?.firstName || ''
  const lastName = auth?.userResult?.lastName || ''
  const profileImage = auth?.userResult?.profileImage || ''

  const handleSetRole = (role) => {
    setRole(role)
    setDATA((prevData) => ({
      ...prevData,
      postedAs: role,
    }))
  }

  return (
    <div className="bg-white px-11">
      <div className="mb-4">
        <div className="flex">
          <h4 className={`${styles.property_label}  mb-2`}>
            {stepFive.propertyDescription}
            <span className="text-red-500 ml-[2px] ">*</span>
          </h4>
          <TooltipComponent tooltipText={stepFive.enterDescription} />
        </div>
        <div>
          <AdvancedEditor
            value={DATA?.propertyDescription}
            onChange={handlePropertyDescriptionChange}
            DATA={DATA}
            setIsAuto={setIsAuto}
            isautoGenerate={true}
          />
        </div>
        <div className="text-primary text-left px-2 py-1  bg-noteBackground rounded-md mt-1 max-w-[550px]">
          <p> {stepFive.generateDescriptionNote}</p>
        </div>
      </div>
      {propertyDescription && propertyDescription.length > 0 && (
        <div>
          <div className=" shadow-lg rounded-lg">
            <SearchResultCardComponent
              isProject={false}
              linkEnabled={false}
              addresslabel={addressLabel}
              bedroomCount={bedroomCount}
              bathroomCount={bathroomCount}
              furnishingStatus={furnishingStatus}
              propertyTitle={propertyTitle}
              salePrice={salePrice}
              rentPrice={rentPrice}
              propertySize={propertySize}
              projectDescription={projectDescription}
              propertyDescription={PropertyDescription}
              propertyType={propertyType}
              projectType={projectType}
              propertySubType={propertySubType}
              projectSubType={projectSubType}
              firstName={firstName}
              lastName={lastName}
              imageArray={imageArray}
              daysAgo={daysAgo}
              profileImage={profileImage}
              propertySizeUnit={propertySizeUnit}
            />
          </div>
        </div>
      )}

      {auth?.userResult?.userType !== agentText && (
        <div className='mt-4'>
          <p className='ml-3'>{stepFive.selectYourRole}</p>
          <div className="flex gap-4">
            <div className="flex justify-center items-center ">
              <Checkbox
                {...label}
                checked={role === ownerText}
                sx={{
                  color: maroon,
                  '&.Mui-checked': {
                    color: '#931602',
                  },
                }}
                onChange={() => handleSetRole(ownerText)}
              />
              <label className='text-[0.875rem] justify-center items-center text-black bg-opacity-5'>
                {stepFive.propertyOwnerText}
              </label>
            </div>
            <div className="flex justify-center items-center ">
              <Checkbox
                {...label}
                checked={role === representativeText}
                sx={{
                  color: maroon,
                  '&.Mui-checked': {
                    color: '#931602',
                  },
                }}
                onChange={() => handleSetRole(representativeText)}
              />
              <label className='text-[0.875rem] justify-center items-center text-black bg-opacity-5'>
                {stepFive.AuthozisedRepresentative}
              </label>
            </div>
          </div>
        </div>
      )}
      <div className="flex mt-4">
        <div className="-mt-2.5 flex items-start">
          <Checkbox
            {...label}
            checked={declarationOne}
            sx={{
              color: maroon,
              '&.Mui-checked': {
                color: '#931602',
              },
            }}
            onChange={() => {
              setDeclarationOne(!declarationOne)
              setDeclarationTwo(!declarationTwo)
            }}
          />
        </div>
        <label className="ml-2 text-sm text-gray-600 font-semibold bg-opacity-5 rounded-[4.95px]">
          {stepFive.reviewedDeclearationText}
        </label>
      </div>
    </div>
  )
}
