import React, { useEffect, useState } from 'react'


import AdvancedEditor from '@/components/PostProperty/advanceFilter'
import SearchResultCardComponent from '@/components/SearchResultCardComponent/SearchResultCardComponent'
import TooltipComponent from '@/components/Tooltip'
import { COMPONENTS } from '@/textV2'
const { POST_PROJECT_COMPO }=COMPONENTS
const { stepFiveText }=POST_PROJECT_COMPO
export default function Step5({
  projectData,
  setProjectData,
  setProjectDetails,
}) {
  const [display, setDisplay] = useState(
    JSON.parse(localStorage.getItem(stepFiveText.displays) || stepFiveText.false)
  )
  const {
    projectTitle,
    projectType,
    projectSubType,
    salePrice,
    projectDescription,
    locality,
    city,
    projectUnits,
    projectAreaUnit,
    projectArea,
    totalUnitCount,
    projectCoverImage,
  } = projectData || {}
  const [isAuto, setIsAuto] = useState(false)

  const handleProjectDescriptionChange = (content) => {
    setProjectData({
      ...projectData,
      projectDescription: content,
      isDescriptionAutoGenerated: isAuto,
    })
    setDisplay(true)
  }

  useEffect(() => {
    localStorage.setItem(stepFiveText.displays, JSON.stringify(display))
    setProjectData({
      ...projectData,
      projectMetaTitle: projectData?.projectTitle
    })
  }, [display])
  useEffect(() => {
    let totalCount = 0
    const { projectUnits } = projectData
    projectUnits?.map((unit) => {
      totalCount += parseInt(unit?.unitCount)
      setProjectData({
        ...projectData,
        totalUnitCount: totalCount,
      })
    })
  }, [])
  let imageArray = []
  projectData?.projectImages?.forEach((element) => {
    imageArray.push(element.url)
  })

  return (
    <div className="px-7 py-2">
      <div className="mb-9">
        <div className="flex">
          <p className={`mb-2 text-[1rem]`}>
            {stepFiveText.projectDescription}
          </p>
          <div className="pt-0.4">
            <TooltipComponent tooltipText={stepFiveText.projectHoverDesc} />
          </div>
          <span className="text-red-500 ml-1 mt-0">*</span>
        </div>
        <div>
          <AdvancedEditor
            value={projectData?.projectDescription}
            onChange={handleProjectDescriptionChange}
            DATA={projectData}
            setIsAuto={setIsAuto}
            isautoGenerate={true}
          />
        </div>
      </div>
      {display && (
        <div className="w-fit shadow-lg rounded-lg">
          <SearchResultCardComponent
            isProject={true}
            linkEnabled={false}
            projectTitle={projectTitle}
            projectType={projectType}
            projectSubType={projectSubType}
            salePrice={salePrice}
            projectDescription={projectDescription}
            locality={locality}
            city={city}
            imageArray={imageArray}
            projectUnits={projectUnits}
            projectAreaUnit={projectAreaUnit}
            projectArea={projectArea}
            totalUnitCount={totalUnitCount}
            projectCoverImage={projectCoverImage}
          />
        </div>
      )}
    </div>
  )
}
