import { GLOBALLY_COMMON_TEXT } from "@/textV2";
import { makeApiRequest } from "@/utils/utils";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
const {getType}=GLOBALLY_COMMON_TEXT.text
const {sScoreCalculationRoute}=GLOBALLY_COMMON_TEXT.routes
const CalculateMscore = () => {
    const [calData, setCalData] = useState(null);
    const router = useRouter()
    const {id} = router.query || {};
    useEffect(() => {
        const fetchMscoreData = async () => {
            try {
                const {data} = await makeApiRequest(getType, `${sScoreCalculationRoute}?id=${id}`);
                setCalData(data);
            } catch (error) {
                console.error('Error fetching M score data:', error);
            }
        };
        fetchMscoreData();
    }, [id]);
 
    return (
        <div>
            {calData ? (
                <div className="ml-5 font-medium">
                    <h1><strong>Calculated M Score </strong></h1>
                    <p><strong>M Score:</strong> <span className="text-primary">{calData?.result?.mScore}</span></p>
                    <p><strong>Nearby Places essentials:</strong> <span className="text-primary">{calData?.result?.pointsAdded?.essentialsScore}</span>/30</p>
                    <p><strong>Nearby Places luxuriesScore:</strong> <span className="text-primary">{calData?.result?.pointsAdded?.luxuriesScore}</span>/15</p>
                    <p><strong>Project Rating:</strong> <span className="text-primary">{calData?.result?.pointsAdded?.ratingScore}</span>/5</p>
                    <p><strong>Modular Kitchen:</strong> <span className="text-primary">{calData?.result?.pointsAdded?.modularKitchenPoints}</span>/1</p>
                    <p><strong>Wardrobe:</strong> <span className="text-primary">{calData?.result?.pointsAdded?.wardrobePoints}</span>/1</p>
                    <p><strong>Furnishing:</strong> <span className="text-primary">{calData?.result?.pointsAdded?.furnishingPoints}</span>/1</p>
                    <p><strong>Flooring:</strong> <span className="text-primary">{calData?.result?.pointsAdded?.flooringPoints}</span>/1</p>
                    <p><strong>Parking:</strong> <span className="text-primary">{calData?.result?.pointsAdded?.totalParkingPoints}</span>/2</p>
                    <p><strong>Balcony View:</strong> <span className="text-primary">{calData?.result?.pointsAdded?.balconyViewPoints}</span>/1</p>
                    <p><strong>Balconies Count:</strong> <span className="text-primary">{calData?.result?.pointsAdded?.balconiesPoints}</span>/1</p>
                    <p><strong>Dedicated Rooms:</strong> <span className="text-primary">{calData?.result?.pointsAdded?.dedicatedRoomPoints}</span>/2</p>
                    <p><strong>Property Age:</strong> <span className="text-primary">{calData?.result?.pointsAdded?.builtDatePoints}</span>/5</p>
                    <p><strong>Amenities:</strong> <span className="text-primary">{calData?.result?.pointsAdded?.amenityCountPoints}</span>/10</p>
                    <p><strong>Image count:</strong> <span className="text-primary">{calData?.result?.pointsAdded?.propertyImagesPoints}</span>/3</p>
                    <p><strong>HD Cover Image:</strong> <span className="text-primary">{calData?.result?.pointsAdded?.hdImagePoints}</span>/2</p>
                    <p><strong>Video:</strong> <span className="text-primary">{calData?.result?.pointsAdded?.propertyVideosPoints}</span>/2</p>
                    <p><strong>Description length:</strong> <span className="text-primary">{calData?.result?.pointsAdded?.propertyDescriptionPoints}</span>/2</p>
                    <p><strong>Auto-Generated Description:</strong> <span className="text-primary">{calData?.result?.pointsAdded?.autoGeneratedDescriptionPoints}</span>/1</p>
                    <p><strong>M-Verified:</strong> <span className="text-primary">{calData?.result?.pointsAdded?.verifiedPoints}</span>/15</p>
                </div>
            ) : (
                <p>Loading...</p>
            )}
        </div>
    );
};

export default CalculateMscore;